# src/explore_pkad.py
"""
Explore the PKAD-R database schema before writing the lookup module.
Run this once to understand the data structure, then use findings to
build pka_lookup.py on Day 8.
"""

import pandas as pd
import os
import glob

# Find the PKAD-R file dynamically
ref_files = glob.glob("data/reference/PKAD-R*.csv")
if not ref_files:
    raise FileNotFoundError("No PKAD-R file found in data/reference/")

pkad_path = ref_files[0]
print(f"Loading: {pkad_path}\n")

try:
    df = pd.read_csv(pkad_path)
    if df.shape[1] < 3:
        raise ValueError("Too few columns — probably tab-separated")
except Exception:
    df = pd.read_csv(pkad_path, sep="\t")

print("=" * 50)
print(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nData types:\n{df.dtypes}")
print(f"\nFirst 5 rows:\n{df.head()}")
print(f"\nMissing values per column:\n{df.isnull().sum()}")

print("\n" + "=" * 50)
print("SAMPLE VALUES PER COLUMN:")
for col in df.columns:
    samples = df[col].dropna().unique()[:5]
    print(f"  {col}: {samples}")

# Key question: what does the protein/residue identifier look like?
print("\n" + "=" * 50)
print("IDENTIFIER ANALYSIS:")

# Checking for PDB ID column
for col in df.columns:
    col_lower = col.lower()
    if any(k in col_lower for k in ["pdb", "protein", "id", "code"]):
        print(f"\n  Possible PDB ID column → '{col}'")
        print(f"  Sample values: {df[col].dropna().unique()[:10]}")

# Checking for chain column
for col in df.columns:
    if "chain" in col.lower():
        print(f"\n  Chain column → '{col}'")
        print(f"  Sample values: {df[col].dropna().unique()[:10]}")

# Checking for residue number
for col in df.columns:
    if any(k in col.lower() for k in ["res", "num", "seq", "position"]):
        print(f"\n  Possible residue column → '{col}'")
        print(f"  Sample values: {df[col].dropna().unique()[:10]}")

# Checking for pKa column — handle text columns safely
for col in df.columns:
    if "pka" in col.lower() or "pk" in col.lower():
        numeric_vals = pd.to_numeric(df[col], errors='coerce').dropna()
        if not numeric_vals.empty:
            print(f"\n  pKa value column → '{col}'")
            print(f"  Min: {numeric_vals.min():.2f}, Max: {numeric_vals.max():.2f}, "
                  f"Mean: {numeric_vals.mean():.2f}")
        else:
            print(f"\n  Non-numeric pKa column → '{col}'")
            print(f"  Sample values: {df[col].dropna().unique()[:5]}")

# Saving findings to a notes file for reference when building pka_lookup.py
notes = f"""
PKAD-R Schema Notes (auto-generated by explore_pkad.py)
=========================================================
File: {pkad_path}
Shape: {df.shape}
Columns: {df.columns.tolist()}
Dtypes:
{df.dtypes.to_string()}

Sample row:
{df.iloc[0].to_string()}
"""

with open("data/reference/PKAD_schema_notes.txt", "w") as f:
    f.write(notes)

print("\nSchema notes saved to data/reference/PKAD_schema_notes.txt")